name: Continuous integration
on: pull_request
jobs:
  ci:
    # Pinned to Ubuntu 22.04 to resolve a Chrome sandbox issue with Ubuntu 24.04.
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cache the node_modules dir
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
    - name: Install
      run: yarn install --frozen-lockfile
    - name: Build
      run: yarn build-prod
    - name: Test
      run: yarn test
